apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-deployment
  labels:
    app: good-deployment
spec:
  replicas: 0 # testing purposes only
  selector:
    matchLabels:
      app: good-deployment
  template:
    metadata:
      labels:
        app: good-deployment
    spec:
      containers:
      - name: good
        image: bash@sha256:0ea6c5ec80900ad1b96c604f9311b2335292a35d6ff1b9d955354d66ce0216c5
