apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sExternalData
metadata:
  name: guac
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
