apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sexternaldata
spec:
  crd:
    spec:
      names:
        kind: K8sExternalData
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sexternaldata

        violation[{"msg": msg}] {
          # build a list of keys containing images
          images := [img | img = input.review.object.spec.template.spec.containers[_].image]

          # send external data request
          response := external_data({"provider": "guac-provider", "keys": images})

          result := response.responses[_]
          result[1] > 0

          msg := sprintf("Image %v blocked due to policy violation", [result[0]])
        }
        
