apiVersion: v1
kind: Service
metadata:
  name: guac-provider
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    run: guac-provider
  sessionAffinity: None
